OUTNAME_RELEASE = sample_algorithm_selector
OUTNAME_DEBUG = sample_algorithm_selector_debug
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
