OUTNAME_RELEASE = sample_reformat_free_io
OUTNAME_DEBUG   = sample_reformat_free_io_debug
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
