OUTNAME_RELEASE = sample_uff_mnist
OUTNAME_DEBUG   = sample_uff_mnist_debug
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
