OUTNAME_RELEASE = sample_fasterRCNN
OUTNAME_DEBUG   = sample_fasterRCNN_debug
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
